
# GREEN='\033[0;32m'
# YELLOW='\033[0;33m'
# RED='\033[0;31m'
# NC='\033[0m' # No Color

# autoSetEth0AndEth1Str="
# #interface file auto-generated by board/renmingrui/post-image.sh\\
# auto eth0\\
# iface eth0 inet dhcp\\
# auto eth1\\
# iface eth1 inet dhcp"

# echo -e "--- ${RED}Starting post-image Script${NC} ---"
# echo -e "${GREEN}Build Dir is: $TARGET_DIR"${NC}

# echo -e "--- ${YELLOW}Adding eth0 and eth1 auto setup${NC} ---"
# echo "grep '#interface file auto-generated by board/renmingrui/post-image.sh' /home/renmingrui/workspace/buildroot/buildroot-2020.08.1/output/target/etc/network/interfaces"
# if grep '#interface file auto-generated by board/renmingrui/post-image.sh' /home/renmingrui/workspace/buildroot/buildroot-2020.08.1/output/target/etc/network/interfaces; then
#     echo "find exit eth0 or eth1 settings, not add new"
# else
#     echo "adding..."
#     echo "sed -ei \"\$a\\${autoSetEth0AndEth1Str}\" $TARGET_DIR/etc/network/interfaces"
#     sed -ie  "\$a\\${autoSetEth0AndEth1Str}" \
#         $TARGET_DIR/etc/network/interfaces
# fi

# echo -e "--- ${YELLOW}Adding eth0 and eth1 auto end${NC} ---"
# echo -e "--- ${RED}End post-image Script${NC} ---"
